analytics: {}
color:
  brandColors:
    - '#C0D8B8'
    - '#204820'
    - '#689050'
    - '#4EB14E'
    - '#000000'
  brandStrength: 0.859695
  lightness: 0.332746
  rhythmicContrast: 0.838548
  saturation: 0.27263
cta: {}
layout_spectrum: 0.606085
name: AxleEthingtonPhotography
opengraph: {}
purpose: []
typography_spectrum: 0.901315
