name: AxleEthingtonPhotography
favicon: null
layout_spectrum: 0.606085
typography_spectrum: 0.901315
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#616161'
    - '#a2a2a2'
    - '#c8c8c8'
    - '#eeeeee'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0
purpose: []
